/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    FormatFilter: typeof import('./components/FormatFilter.vue')['default']
    FormatItem: typeof import('./components/FormatItem.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    HomeUrlSetter: typeof import('./components/HomeUrlSetter.vue')['default']
    MainBar: typeof import('./components/MainBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UrlSetter: typeof import('./components/UrlSetter.vue')['default']
  }
}
